export const INCREASE_ICE_CREAM_QTY = 'INCREASE_ICE_CREAM_QTY';
export const DECREASE_ICE_CREAM_QTY = 'DECREASE_ICE_CREAM_QTY';
export const RESET_ICE_CREAM_QTY = 'RESET_ICE_CREAM_QTY';
export const SET_ICE_CREAM_QTY = 'SET_ICE_CREAM_QTY';
